day74 课上笔记以及代码/代码/supercrm/sales/urls.py
from django.conf.urls import url
from django.contrib import admin
from sales.views import (
    auth,customer
)

urlpatterns = [

    # 登录
    url(r'^login/', auth.login,name='login'),
    # 注册
    url(r'^register/', auth.register,name='register'),
    # 首页
    url(r'^home/', customer.home,name='home'),

    #所有客户信息展示  #http://127.0.0.1:8000/customers/4/?page=3
    # url(r'^customers/(\d+)/', views.customers,name='customers'),
    # url(r'^customers/', views.customers,name='customers'),
    url(r'^customers/', customer.CutomerView.as_view(),name='customers'),
    # 我的客户
    url(r'^mycustomers/', customer.CutomerView.as_view(),name='mycustomers'),

    # 添加客户
    # url(r'^add_customer/', views.add_customer,name='add_customer'),
    url(r'^add_customer/', customer.add_edit_customer,name='add_customer'),
    # 编辑客户
    # url(r'^edit_customer/(\d+)/', views.edit_customer,name='edit_customer'),
    url(r'^edit_customer/(\d+)/', customer.add_edit_customer,name='edit_customer'),

    # 跟进记录展示
    url(r'^consult_record/', customer.ConsultRecordView.as_view(),name='consult_record'),

    # 添加跟进记录
    url(r'^add_consult_record/', customer.AddEditConsultView.as_view(),name='add_consult_record'),
    # 编辑跟进记录
    url(r'^edit_consult_record/(\d+)/', customer.AddEditConsultView.as_view(),name='edit_consult_record'),

    # 报名表信息展示
    url(r'^enrollment/', customer.EnrollmentView.as_view(),name='enrollment'),

    #编辑和添加报名信息
    url(r'^enroll_add/', customer.AddEditEnrollView.as_view(),name='enroll_add'),
    url(r'^enroll_edit/(\d+)/', customer.AddEditEnrollView.as_view(),name='enroll_edit'),

    # 课程记录
    url(r'^course_record/', customer.CourseRecordView.as_view(),name='course_record'),




]

day74 课上笔记以及代码/代码/supercrm/supercrm/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # crm相关业务
    url(r'^crm/', include('sales.urls')),


]

day74 课上笔记以及代码/代码/supercrm/sales/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe
# Create your models here.

course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class UserInfo(models.Model):
    """
    用户表：销售\讲师、班主任
    """
    username = models.CharField(max_length=16)
    password = models.CharField(max_length=32)
    email = models.EmailField()
    telephone = models.CharField(max_length=16)
    is_active = models.BooleanField(default=True)
    def __str__(self):
        return self.username

class Customer(models.Model):
    """
    客户表（最开始的时候大家都是客户，销售就不停的撩你，你还没交钱就是个客户）
    """
    qq = models.CharField(verbose_name='QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True) #requierd:False
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名') #可为空，有些人就不愿意给自己的真实姓名
    sex_type = (('male', '男'), ('female', '女')) #
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True) #存的是male或者female，字符串
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True) #手机号改成字符串的，不然不好搜索
    # phone = models.CharField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')

    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)  #self指的就是自己这个表，和下面写法是一样的效果
    # '''
    # id  name introduce_from
    # 1   dz   None
    # 2   xf   1
    # 3   cg   1
    #
    # '''


    # introduce_from = models.ForeignKey('Customer', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices) #多选，并且存成一个列表的格式,通过modelform来用的时候，会成为一个多选框

    # course = models.CharField("咨询课程", choices=course_choices) #如果你不想用上面的多选功能，可以使用Charfield来存
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",help_text="选择客户此时的状态") #help_text这种参数基本都是针对admin应用里面用的

    date = models.DateTimeField("咨询日期", auto_now_add=True) #这个没啥用昂，我问销售，销售说是为了一周年的时候给客户发一个祝福信息啥的
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True) #考核销售的跟进情况，如果多天没有跟进，会影响销售的绩效等
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True) #销售自己大概记录一下自己下一次会什么时候跟进，也没啥用

    #用户表中存放的是自己公司的所有员工。
    consultant = models.ForeignKey('UserInfo', verbose_name="销售", related_name='customers', blank=True, null=True,on_delete=models.CASCADE )


    #一个客户可以报多个班，报个脱产班，再报个周末班等，所以是多对多。
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级",blank=True)

    class Meta:
        ordering = ['id',]
        verbose_name='客户信息表'
        verbose_name_plural = '客户信息表'

    def __str__(self):
        return self.name+":"+self.qq

    enroll_status_choices = (('signed', "已报名"),
                             ('unregistered', "未报名"),
                             ('studying', '学习中'),
                             ('paid_in_full', "学费已交齐"))
    def status_show(self):
        status_color = {
            'paid_in_full':'green',
            'unregistered':'red',
            'studying':'lightblue',
            'signed':'yellow',
        }

        return mark_safe("<span style='background-color:{0}'>{1}</span>".format(status_color[self.status],self.get_status_display()))
    # def get_classlist(self):  #当我们通过self.get_classlist的时候，就拿到了所有的班级信息，前端显示的时候用
    #
    #     l=[]
    #     for cls in self.class_list.all():
    #         l.append(str(cls))
    #     return mark_safe(",".join(l)) #纯文本，不用mark_safe也可以昂

class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name



class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期") #python20期等
    campuses = models.ForeignKey('Campuses', verbose_name="校区",on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True) #不一定什么时候结业，哈哈，所以可为空

    #contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserInfo', verbose_name="老师") #对了，还有一点，如果你用的django2版本的，那么外键字段都需要自行写上on_delete=models.CASCADE

    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)


############################下面的表以后再说#################################

# class ContractTemplate(models.Model):
#     """
#     合同模板表
#     """
#     name = models.CharField("合同名称", max_length=128, unique=True)
#     content = models.TextField("合同内容")
#     date = models.DateField(auto_now=True)
#
#

class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserInfo", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    # def __str__(self):



class Enrollment(models.Model):
    """
    报名表
    """
    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    # contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campuses')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')

    def __str__(self):
        return self.customer.name
# class PaymentRecord(models.Model):
#     """
#     缴费记录表
#     """
#     pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
#     paid_fee = models.IntegerField("费用数额", default=0)
#     note = models.TextField("备注", blank=True, null=True)
#     date = models.DateTimeField("交款日期", auto_now_add=True)
#     course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
#     class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
#                                   default='N/A')
#     enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True)
#     customer = models.ForeignKey('Customer', verbose_name="客户")
#     consultant = models.ForeignKey('UserProfile', verbose_name="销售")
#     delete_status = models.BooleanField(verbose_name='删除状态', default=False)
#
#     status_choices = (
#         (1, '未审核'),
#         (2, '已审核'),
#     )
#     status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)
#
#     confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)

day74 课上笔记以及代码/代码/supercrm/sales/templates/saleshtml/add_customer.html
{% extends 'starter.html' %}

{% block content %}


  <form class="form-horizontal" novalidate method="post">
    {% csrf_token %}
    {% for field in customer_form %}
      <div class="form-group">
          <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
          <div class="col-sm-6">
            {{ field }}
          </div>
          <div class="col-sm-4">
            {{ field.errors.0 }}
          </div>
        </div>
    {% endfor %}
    <button class="btn btn-success">提交</button>

  </form>


{% endblock %}

day74 课上笔记以及代码/代码/supercrm/sales/templates/saleshtml/add_edit_consult.html
{% extends 'starter.html' %}

{% block title %}
        <h1>
{#          {{ label }} #}
        </h1>
{% endblock %}

{% block content %}


  <form class="form-horizontal" novalidate method="post" action="">
    {% csrf_token %}
    {% for field in consult_form %}
      <div class="form-group">
          <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
          <div class="col-sm-6">
            {{ field }}
          </div>
          <div class="col-sm-4">
            {{ field.errors.0 }}
          </div>
        </div>
    {% endfor %}
    <button class="btn btn-success">提交</button>

  </form>


{% endblock %}

day74 课上笔记以及代码/代码/supercrm/sales/templates/saleshtml/add_edit_enroll.html
{% extends 'starter.html' %}

{% block title %}
        <h1>
          {{ label }}
        </h1>
{% endblock %}

{% block content %}


  <form class="form-horizontal" novalidate method="post" action="">
    {% csrf_token %}
    {% for field in enroll_form %}
      <div class="form-group">
          <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
          <div class="col-sm-6">
            {{ field }}
          </div>
          <div class="col-sm-4">
            {{ field.errors.0 }}
          </div>
        </div>
    {% endfor %}
    <button class="btn btn-success">提交</button>

  </form>


{% endblock %}

day74 课上笔记以及代码/代码/supercrm/sales/templates/saleshtml/consultrecord.html
{% extends 'starter.html' %}

{% block title %}
  <h1>
{#    {% if tag == '1' %}#}
{#      公户信息#}
{#    {% else %}#}
{#      我的客户信息#}
{#    {% endif %}#}
  {% load mytags %}
{#  {% reverse_url request %}#}
    跟进记录展示
  </h1>
{% endblock %}

{% block content %}
  <a href="{% url 'add_consult_record' %}" class="btn btn-primary">
    添加跟进记录
  </a>
  <div class="form-inline">

    <form action="" class="pull-right">
      <div class="form-group ">
        <select name="search_field" id="search_field" class="form-control">
          <option value="customer__name__contains">客户名称</option>
{#          <option value="name__contains">name</option>#}
          <!--  search_field:name  kw:1111  filter(name=1111) -->

        </select>
        <input type="text" class="form-control" id="key_word" placeholder="请输入搜索内容" name="kw">
        <button type="submit" class="btn btn-default">搜索</button>
      </div>

    </form>

  </div>
  <form action="" method="post">
      {% csrf_token %}
      <div class="form-group pull-left">
        <select name="action" id="action" class="form-control">

            <option value="bulk_delete">批量删除</option>

        </select>

      </div >
      <button class="btn btn-warning">go</button>
    <table class="table table-striped table-hover table-bordered"
  >
  <thead>
  <tr>
    <th><input type="checkbox" id="select_all">选择</th>
    <th>序号</th>
    <th>所咨询客户</th>
    <th>跟进内容</th>
    <th>跟进状态</th>
    <th>跟进人</th>
    <th>跟进日期</th>
    <th>操作</th>

  </tr>
  </thead>
  <tbody>
  {% for consult in consult_list %}
    <tr>
      <td>
        <input type="checkbox" name="cids" value="{{ consult.pk }}">
      </td>
      <td>{{ forloop.counter }}</td>
      <td>{{ consult.customer }}</td>
      <td>{{ consult.note }}</td>
      <td>{{ consult.get_status_display }}</td>
      <td>{{ consult.consultant }}</td>
      <td>{{ consult.date|date:'Y-m-d H:i:s' }}</td>
      <td>
{#        <a href="{% url 'edit_customer' customer_obj.pk %}?next=/customers/?page=3"><i class="fa fa-edit"></i></a>#}
{#        <a href="{% resole_url request 'edit_customer' customer_obj.pk %}"><i class="fa fa-edit"></i></a>#}
        <a href="{% resole_url request 'edit_consult_record' consult.pk %}"><i class="fa fa-edit"></i></a>
        <a href=""><i class="fa fa-remove"></i></a>
      </td>

    </tr>
  {% endfor %}

  </tbody>
  </table>

    {{ page_html }}
  </form>
{#  {{ page_html|safe }}#}


{#  <nav aria-label="Page navigation">#}
{#    <ul class="pagination">#}
{#      <li>#}
{#        <a href="#" aria-label="Previous">#}
{#          <span aria-hidden="true">&laquo;</span>#}
{#        </a>#}
{#      </li>#}
{#      {% for i in page_num_range %}#}
{#        <li><a href="/customers/?page={{ i }}">{{ i }}</a></li>#}
{#      {% endfor %}#}
{##}
{#      <li>#}
{#        <a href="#" aria-label="Next">#}
{#          <span aria-hidden="true">&raquo;</span>#}
{#        </a>#}
{#      </li>#}
{#    </ul>#}
{#  </nav>#}

{% endblock %}

day74 课上笔记以及代码/代码/supercrm/sales/templates/saleshtml/courserecord.html
{% extends 'starter.html' %}

{% block title %}
  <h1>
  课程记录展示
  {% load mytags %}


  </h1>
{% endblock %}

{% block content %}
  <a href="" class="btn btn-primary">
    添加课程记录
  </a>
  <div class="form-inline">

    <form action="" class="pull-right">
      <div class="form-group ">
        <select name="search_field" id="search_field" class="form-control">
          <option value="qq__contains">qq</option>
          <option value="name__contains">name</option>
          <!--  search_field:name  kw:1111  filter(name=1111) -->

        </select>
        <input type="text" class="form-control" id="key_word" placeholder="请输入搜索内容" name="kw">
        <button type="submit" class="btn btn-default">搜索</button>
      </div>

    </form>

  </div>
  <form action="" method="post">
      {% csrf_token %}
      <div class="form-group pull-left">
        <select name="action" id="action" class="form-control">

          <option value="">批量删除</option>



        </select>
      </div >
      <button class="btn btn-warning">go</button>
    <table class="table table-striped table-hover table-bordered"
  >
  <thead>
  <tr>
    <th><input type="checkbox" id="select_all">选择</th>
    <th>序号</th>
    <th>节次</th>
    <th>上课日期</th>
    <th>本节课程标题</th>
    <th>班级</th>
    <th>讲师</th>

    <th>操作</th>

  </tr>
  </thead>
  <tbody>
  {% for course_record in course_records %}
    <tr>
      <td>
        <input type="checkbox" name="cids" value="{{ course_record.pk }}">
      </td>
      <td>{{ forloop.counter }}</td>
      <td>{{ course_record.day_num }}</td>
      <td>{{ course_record.date|date:'Y-m-d' }}</td>
      <td>{{ course_record.course_title }}</td>
      <td>{{ course_record.re_class }}</td>
      <td>{{ course_record.teacher }}</td>

      <td>
{#        <a href="{% url 'edit_customer' customer_obj.pk %}?next=/customers/?page=3"><i class="fa fa-edit"></i></a>#}
        <a href=""><i class="fa fa-edit"></i></a>
      </td>

    </tr>
  {% endfor %}

  </tbody>
  </table>

    {{ page_html }}
  </form>
{#  {{ page_html|safe }}#}


{#  <nav aria-label="Page navigation">#}
{#    <ul class="pagination">#}
{#      <li>#}
{#        <a href="#" aria-label="Previous">#}
{#          <span aria-hidden="true">&laquo;</span>#}
{#        </a>#}
{#      </li>#}
{#      {% for i in page_num_range %}#}
{#        <li><a href="/customers/?page={{ i }}">{{ i }}</a></li>#}
{#      {% endfor %}#}
{##}
{#      <li>#}
{#        <a href="#" aria-label="Next">#}
{#          <span aria-hidden="true">&raquo;</span>#}
{#        </a>#}
{#      </li>#}
{#    </ul>#}
{#  </nav>#}

{% endblock %}

day74 课上笔记以及代码/代码/supercrm/sales/templates/saleshtml/customers.html
{% extends 'starter.html' %}

{% block title %}
  <h1>
{#    {% if tag == '1' %}#}
{#      公户信息#}
{#    {% else %}#}
{#      我的客户信息#}
{#    {% endif %}#}
  {% load mytags %}
  {% reverse_url request %}

  </h1>
{% endblock %}

{% block content %}
  <a href="{% url 'add_customer' %}" class="btn btn-primary">
    添加客户
  </a>
  <div class="form-inline">

    <form action="" class="pull-right">
      <div class="form-group ">
        <select name="search_field" id="search_field" class="form-control">
          <option value="qq__contains">qq</option>
          <option value="name__contains">name</option>
          <!--  search_field:name  kw:1111  filter(name=1111) -->

        </select>
        <input type="text" class="form-control" id="key_word" placeholder="请输入搜索内容" name="kw">
        <button type="submit" class="btn btn-default">搜索</button>
      </div>

    </form>

  </div>
  <form action="" method="post">
      {% csrf_token %}
      <div class="form-group pull-left">
        <select name="action" id="action" class="form-control">
          {% if tag == '1' %}
            <option value="reverse_gs">公户转私户</option>
          {% else %}
            <option value="reverse_sg">私户转公户</option>
          {% endif %}


        </select>
      </div >
      <button class="btn btn-warning">go</button>
    <table class="table table-striped table-hover table-bordered"
  >
  <thead>
  <tr>
    <th><input type="checkbox" id="select_all">选择</th>
    <th>序号</th>
    <th>id</th>
    <th>qq</th>
    <th>姓名</th>
    <th>性别</th>
    <th>报名状态</th>
    <th>转介绍自学员</th>
    <th>跟进记录</th>
    <th>销售</th>
    <th>操作</th>

  </tr>
  </thead>
  <tbody>
  {% for customer_obj in customer_objs %}
    <tr>
      <td>
        <input type="checkbox" name="cids" value="{{ customer_obj.pk }}">
      </td>
      <td>{{ forloop.counter }}</td>
      <td>{{ customer_obj.pk }}</td>
      <td>{{ customer_obj.qq }}</td>
      <td>{{ customer_obj.name }}</td>
      <td>{{ customer_obj.get_sex_display }}</td>
      <td>{{ customer_obj.status_show }}</td>
      <td>{{ customer_obj.introduce_from|default:'无' }}</td>
      <td>
        <a href="{% url 'consult_record' %}?cid={{ customer_obj.pk }}">查看详情</a>
      </td>
      <td>{{ customer_obj.consultant|default:'暂无' }}</td>
      <td>
{#        <a href="{% url 'edit_customer' customer_obj.pk %}?next=/customers/?page=3"><i class="fa fa-edit"></i></a>#}
        <a href="{% resole_url request 'edit_customer' customer_obj.pk %}"><i class="fa fa-edit"></i>xxx</a>
      </td>

    </tr>
  {% endfor %}

  </tbody>
  </table>

    {{ page_html }}
  </form>
{#  {{ page_html|safe }}#}


{#  <nav aria-label="Page navigation">#}
{#    <ul class="pagination">#}
{#      <li>#}
{#        <a href="#" aria-label="Previous">#}
{#          <span aria-hidden="true">&laquo;</span>#}
{#        </a>#}
{#      </li>#}
{#      {% for i in page_num_range %}#}
{#        <li><a href="/customers/?page={{ i }}">{{ i }}</a></li>#}
{#      {% endfor %}#}
{##}
{#      <li>#}
{#        <a href="#" aria-label="Next">#}
{#          <span aria-hidden="true">&raquo;</span>#}
{#        </a>#}
{#      </li>#}
{#    </ul>#}
{#  </nav>#}

{% endblock %}

day74 课上笔记以及代码/代码/supercrm/sales/templates/saleshtml/edit_customer.html
{% extends 'starter.html' %}

{% block title %}
        <h1>
          {{ label }}
        </h1>
{% endblock %}

{% block content %}


  <form class="form-horizontal" novalidate method="post" action="">
    {% csrf_token %}
    {% for field in customer_form %}
      <div class="form-group">
          <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
          <div class="col-sm-6">
            {{ field }}
          </div>
          <div class="col-sm-4">
            {{ field.errors.0 }}
          </div>
        </div>
    {% endfor %}
    <button class="btn btn-success">提交</button>

  </form>


{% endblock %}

day74 课上笔记以及代码/代码/supercrm/sales/templates/saleshtml/home.html
{% extends 'starter.html' %}