day79 课上笔记以及代码/代码/luffy_permission01/luffy_permission/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from web.views import auth
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('web.urls')),
    url(r'^rbac/', include('rbac.urls',namespace='rbac')),
    # url(r'^xx', auth.xx,name='xx'),
]

day79 课上笔记以及代码/代码/luffy_permission01/rbac/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from rbac import views

urlpatterns = [
    #角色展示

    url(r'^role/list/', views.role_list,name='role_list'),
    url(r'^role/add/', views.role_add_edit,name='role_add'),
    url(r'^role/edit/(\d+)/', views.role_add_edit,name='role_edit'),
    url(r'^role/del/(\d+)/', views.role_del,name='role_del'),


    url(r'^menu/list/', views.menu_list,name='menu_list'),
    url(r'^menu/add/', views.menu_add_edit,name='menu_add'),
    url(r'^menu/edit/(\d+)/', views.menu_add_edit,name='menu_edit'),
    url(r'^menu/del/(\d+)/', views.menu_del,name='menu_del'),

    #批量增删改 权限
    url(r'^multi/permissions/$', views.multi_permissions, name='multi_permissions'),
    # 权限分配
    url(r'^distribute/permissions/$', views.distribute_permissions, name='distribute_permissions'),



]

day79 课上笔记以及代码/代码/luffy_permission01/web/urls.py
from django.conf.urls import url
from web.views import customer
from web.views import payment
from web.views import auth


urlpatterns = [

    url(r'^login/$', auth.login,name='login'),
    url(r'^index/$', auth.index,name='index'),

    url(r'^nashui/list/$', customer.nashui,name='nashui'),

    url(r'^customer/list/$', customer.customer_list,name='customer_list'),
    url(r'^customer/add/$', customer.customer_add,name='customer_add'),
    url(r'^customer/edit/(?P<cid>\d+)/$', customer.customer_edit,name='customer_edit'),
    url(r'^customer/del/(?P<cid>\d+)/$', customer.customer_del,name='customer_del'),

    url(r'^payment/list/$', payment.payment_list,name='payment_list'),
    url(r'^payment/add/$', payment.payment_add,name='payment_add'),
    url(r'^payment/edit/(?P<pid>\d+)/$', payment.payment_edit,name='payment_edit'),
    url(r'^payment/del/(?P<pid>\d+)/$', payment.payment_del,name='payment_del'),



]

day79 课上笔记以及代码/代码/luffy_permission01/rbac/forms.py
from django import forms
from rbac import models

# 批量权限使用的form
class MultiPermissionForm(forms.ModelForm):
    class Meta:
        model = models.Permission
        fields = ['title', 'url', 'url_name', 'parent', 'menus']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})
        self.fields['parent'].choices = [(None, '-------')] + list(
            models.Permission.objects.filter(parent__isnull=True).exclude(
                menus__isnull=True).values_list('id', 'title'))

    def clean(self):
        menu = self.cleaned_data.get('menu')
        pid = self.cleaned_data.get('parent')

        if menu and pid:
            raise forms.ValidationError('菜单和根权限同时只能选择一个')
        return self.cleaned_data

day79 课上笔记以及代码/代码/luffy_permission01/rbac/serve/routes.py
from django.conf import settings
from django.utils.module_loading import import_string
from django.urls import RegexURLResolver, RegexURLPattern
from collections import OrderedDict



def recursion_urls(pre_namespace, pre_url, urlpatterns, url_ordered_dict):
    #None, "/", urlpatterns, url_ordered_dict

    # 递归第二层
    #'rbac', "/", rbac.urls.urlpatterns, url_ordered_dict
    """
           [

               url(r'^', include('web.urls')),--RegexURLResolver
               url(r'^rbac/', include('rbac.urls',namespace='rbac')), -- RegexURLResolver
               url(r'^xx', auth.xx,name='xx') -- RegexURLPattern
           ]

    """
    for item in urlpatterns: #w eb.urls.urlpatterns
        '''
            [
                 # url(r'^login/$', auth.login,name='login'), -- RegexURLPattern 
                 url(r'^role/list/', views.role_list,name='role_list'),

            ]
        '''
        if isinstance(item, RegexURLResolver):
            if pre_namespace:
                if item.namespace:
                    namespace = "%s:%s" % (pre_namespace, item.namespace,) #'rbac':'rbac'
                else:
                    namespace = pre_namespace # 'rbac'
            else:
                if item.namespace: #'rbac'
                    namespace = item.namespace #'rbac'
                else:
                    namespace = None
            # None, "/^", urlpatterns, url_ordered_dict
            recursion_urls(namespace, pre_url + item.regex.pattern, item.url_patterns, url_ordered_dict)
            #'/'+'^'--'/^',
        else:

            if pre_namespace: #None
                name = "%s:%s" % (pre_namespace, item.name,)
            else:
                name = item.name #name = 'login'
            if not item.name:
                raise Exception('URL路由中必须设置name属性')

            url = pre_url + item._regex #'^login/$'--  #/^^login/$
            url_ordered_dict[name] = {'url_name': name, 'url': url.replace('^', '').replace('$', '')} #
            #url_ordered_dict['login'] = {'name': 'login', 'url': url.replace('^', '').replace('$', '')} #/login/

def get_all_url_dict(ignore_namespace_list=None):
    """
    获取路由中
    :return:
    """
    ignore_list = ignore_namespace_list or []
    #ignore_list -- ['admin', ]

    #存放项目所有 url路由用的有序字典
    url_ordered_dict = OrderedDict()

    md = import_string(settings.ROOT_URLCONF)

    urlpatterns = []
    # urlpatterns = [
    #     url(r'^', include('web.urls')),
    #     url(r'^rbac/', include('rbac.urls', namespace='rbac')),
    # ]

    print(md.urlpatterns)
    for item in md.urlpatterns:
        """
        [
            
            url(r'^', include('web.urls')),--RegexURLResolver
            url(r'^rbac/', include('rbac.urls',namespace='rbac')), -- RegexURLResolver
            url(r'^xx', auth.xx,name='xx') -- RegexURLPattern
        ]
        
        """
        # [RegexURLResolver,RegexURLResolver,RegexURLPattern]
        if isinstance(item, RegexURLResolver) and item.namespace in ignore_list:
            continue
        urlpatterns.append(item)
    recursion_urls(None, "/", urlpatterns, url_ordered_dict)
    print('>>>>',url_ordered_dict)
    return url_ordered_dict

day79 课上笔记以及代码/代码/luffy_permission01/rbac/views.py
from django.shortcuts import render,HttpResponse,redirect
from rbac import models
from django.db.models import Q
from django import forms

# Create your views here.


def role_list(request):
    all_roles = models.Role.objects.all()
    return render(request,'rbac/role_list.html',{'all_roles':all_roles})


class RoleForm(forms.ModelForm):
    class Meta:
        model = models.Role
        fields = '__all__'
        exclude = ['permissions',]
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'})
        }



def role_add_edit(request,rid=None):

    role_obj = models.Role.objects.filter(pk=rid).first()
    if request.method == 'GET':
        form_obj = RoleForm(instance=role_obj)

        return render(request,'rbac/form.html',{'form_obj':form_obj})
    else:
        form_obj = RoleForm(request.POST,instance=role_obj)
        if form_obj.is_valid():
            form_obj.save()
            return redirect('role_list')
        else:
            return render(request, 'rbac/form.html', {'form_obj': form_obj})

def role_del(request,rid):
    models.Role.objects.filter(pk=rid).delete()
    return redirect('role_list')


def menu_list(request):
    mid = request.GET.get('mid')

    all_menus = models.Menu.objects.all()
    if mid:
        all_permissions = models.Permission.objects.filter(Q(menus_id=mid)|Q(parent__menus_id=mid)).values('id','url','title','menus__title','menus_id','parent_id','parent__title','url_name')
    else:
        all_permissions = models.Permission.objects.all().values('id','url','title','menus_id','parent_id','menus__title','parent__title','url_name')
    # print(all_permissions)
    '''
        {
            pid:{
                'url':xx,
                'children':[
                    {'url'}
                ]
            },
            pid:{
                'url':xx,
                'children':[
                    {'url'}
                ]
            }
        }
    
    '''
    permission_dict = {}
    for i in all_permissions:
        if i.get('menus_id'):
            permission_dict[i['id']] = i
            i['children'] = []
    for k in all_permissions:
        pid = k.get('parent_id')
        if pid:
            permission_dict[pid]['children'].append(k)

    print('permission_dict',permission_dict)


    return render(request,'rbac/menu_list.html',{'all_menus':all_menus,'permission_dict':permission_dict.values(),'mid':mid})


from rbac.icon_data import icon_list
from django.utils.safestring import mark_safe

class MenuForm(forms.ModelForm):
    class Meta:
        model = models.Menu
        fields = '__all__'
        # exclude = ['permissions',]
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'weight':forms.TextInput(attrs={'class':'form-control'}),
            'icon':forms.RadioSelect(choices=[[i[0],mark_safe(i[1])] for i in icon_list]),
        }



def menu_add_edit(request,mid=None):

    menu_obj = models.Menu.objects.filter(pk=mid).first()
    if request.method == 'GET':
        form_obj = MenuForm(instance=menu_obj)
        return render(request,'rbac/form.html',{'form_obj':form_obj})
    else:
        form_obj = MenuForm(request.POST,instance=menu_obj)
        if form_obj.is_valid():
            form_obj.save()
            return redirect('rbac:menu_list')
        else:
            return render(request, 'rbac/form.html', {'form_obj': form_obj})

#删除菜单
def menu_del(request,mid):
    models.Menu.objects.filter(pk=mid).delete()
    return redirect('rbac:menu_list')


from django.forms import modelformset_factory,formset_factory
from rbac.forms import  MultiPermissionForm
from rbac.serve.routes import get_all_url_dict

# 批量权限处理
def multi_permissions(request):
    """
    批量操作权限
    :param request:
    :return:
    """

    post_type = request.GET.get('type')  # 'add'

    # 更新和编辑用的
    FormSet = modelformset_factory(models.Permission, MultiPermissionForm, extra=0)

    # 增加用的
    AddFormSet = formset_factory(MultiPermissionForm, extra=0)

    # 查询出数据库中目前已经存在的所有的url路径(权限)
    permissions = models.Permission.objects.all()


    # 获取路由系统中所有URL
    router_dict = get_all_url_dict(ignore_namespace_list=['admin', ])

    # 数据库中的所有权限的别名
    permissions_name_set = set([i.url_name for i in permissions])

    # 路由系统中的所有权限的别名
    router_name_set = set(router_dict.keys())

    if request.method == 'POST' and post_type == 'add':
        add_formset = AddFormSet(request.POST)
        print('xxxxxxxxxxxxxxxxxxx')
        if add_formset.is_valid():
            print('???',add_formset.cleaned_data)
            permission_obj_list = [models.Permission(**i) for i in add_formset.cleaned_data]

            query_list = models.Permission.objects.bulk_create(permission_obj_list)

            for i in query_list:
                permissions_name_set.add(i.url_name)
        print(add_formset.errors)
    add_name_set = router_name_set - permissions_name_set
    add_formset = AddFormSet(initial=[row for name, row in router_dict.items() if name in add_name_set])
    # initial = [  {
    # 	'name': 'login',
    # 	'url': '/login/'
    # },
    # {
    # 	'name': 'index',
    # 	'url': '/index/'
    # } ]
    del_name_set = permissions_name_set - router_name_set
    del_formset = FormSet(queryset=models.Permission.objects.filter(url_name__in=del_name_set))

    update_name_set = permissions_name_set & router_name_set
    update_formset = FormSet(queryset=models.Permission.objects.filter(url_name__in=update_name_set))

    if request.method == 'POST' and post_type == 'update':
        update_formset = FormSet(request.POST)
        if update_formset.is_valid():
            update_formset.save()
            update_formset = FormSet(queryset=models.Permission.objects.filter(url_name__in=update_name_set))

    return render(
        request,
        'rbac/multi_permissions.html',
        {
            'del_formset': del_formset,
            'update_formset': update_formset,
            'add_formset': add_formset,
        }
    )


def distribute_permissions(request):
    """
    分配权限
    :param request:
    :return:
    """
    uid = request.GET.get('uid')
    rid = request.GET.get('rid')

    if request.method == 'POST' and request.POST.get('postType') == 'role':
        user = models.Userinfo.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        user.roles.set(request.POST.getlist('roles'))

    if request.method == 'POST' and request.POST.get('postType') == 'permission' and rid:
        role = models.Role.objects.filter(id=rid).first()
        if not role:
            return HttpResponse('角色不存在')
        role.permissions.set(request.POST.getlist('permissions'))

    # 所有用户
    user_list = models.Userinfo.objects.all()

    user_has_roles = models.Userinfo.objects.filter(id=uid).values('id', 'roles')

    print('user_has_roles',user_has_roles)
    # print(user_has_roles)
    #<QuerySet [{'id': 1, 'roles': 4}, {'id': 1, 'roles': 6}]>

    user_has_roles_dict = {item['roles']: None for item in user_has_roles}
    #{'4'：None,'6'：None,}  ['4','6']


    """
    用户拥有的角色id
    user_has_roles_dict = { 角色id：None }
    """

    role_list = models.Role.objects.all()

    if rid:
        role_has_permissions = models.Role.objects.filter(id=rid).values('id', 'permissions')
        #[{'id':1,'permissions':2},{'id':1,'permissions':4}]
    elif uid and not rid:
        user = models.Userinfo.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        role_has_permissions = user.roles.values('id', 'permissions')
    else:
        role_has_permissions = []

    print(role_has_permissions)

    role_has_permissions_dict = {item['permissions']: None for item in role_has_permissions}
    #{'4'：None,'6'：None,}
    """
    角色拥有的权限id
    role_has_permissions_dict = { 权限id：None }
    """

    all_menu_list = []

    queryset = models.Menu.objects.values('id', 'title')
    # [{'id':1,'title':'客户管理','children':[]},{'id':2,'title':'班级管理',}]
    menu_dict = {}

    '''
    all_menu_list = [
        {'id':1,'title':'客户管理','children':[
            {'id':1, 'title':'客户展示', 'menus_id':1,'children':[
               {'id':1, 'title':'客户添加', 'menus_id':1,}
            ]} -- 二级菜单对应的那条权限记录
        ]},
        {'id':2,'title':'xx管理','children':[]},
        # {'id': None, 'title': '其他', 'children': []}
    ]
    
    menu_dict = {
        一级菜单权限id-
        1:{'id':1,'title':'客户管理','children':[
            {'id':1, 'title':'客户展示', 'menus_id':1,'children':[
                {'id':1, 'title':'客户添加', 'menus_id':1,}
            ]} -- 二级菜单对应的那条权限记录
        ]},
        2:{'id':2,'title':'xx管理','children':[]},
        None:{'id': None, 'title': '其他', 'children': []},
    }
    '''

    for item in queryset:
        item['children'] = []  # 放二级菜单，父权限
        menu_dict[item['id']] = item
        all_menu_list.append(item)

    other = {'id': None, 'title': '其他', 'children': []}
    all_menu_list.append(other)
    menu_dict[None] = other

    root_permission = models.Permission.objects.filter(menus__isnull=False).values('id', 'title', 'menus_id')
    # [{'id':1, 'title':'客户展示', 'menus_id':1,'children':[]},{'id':2, 'title':'角色展示', 'menus_id':2}]
    root_permission_dict = {}
    '''
    root_permission_dict = {
        二级菜单权限id:{'id':1, 'title':'客户展示', 'menus_id':1,'children':[
            {'id':1, 'title':'客户添加', 'menus_id':1,}
        ]}
        
    }
    '''


    for per in root_permission:
        # per-- {'id':1, 'title':'客户展示', 'menus_id':1，children:[]}
        per['children'] = []  # 放子权限
        nid = per['id']  #二级菜单权限id
        menu_id = per['menus_id'] #一级菜单权限id
        root_permission_dict[nid] = per
        menu_dict[menu_id]['children'].append(per)

    node_permission = models.Permission.objects.filter(menus__isnull=True).values('id', 'title', 'parent_id')

    for per in node_permission:
        pid = per['parent_id']  # 1
        if not pid:

day79 课上笔记以及代码/代码/luffy_permission01/rbac/templates/rbac/bread.html
  {% for crumb in bread_crumbs %}
    {% if crumb.url %}
      <li><a href="{{ crumb.url }}" >{{ crumb.title }}</a></li>
    {% else %}
      <li class="active">{{ crumb.title }}</li>
    {% endif %}
  {% endfor %}

day79 课上笔记以及代码/代码/luffy_permission01/rbac/templates/rbac/distribute_permissions.html
{% extends 'layout.html' %}
{% load mytags %}
{% block css %}
    <style>
        .user-area ul {
            padding-left: 20px;
        }

        .user-area li {
            cursor: pointer;
            padding: 2px 0;
        }

        .user-area li a {
            display: block;
        }

        .user-area li.active {
            font-weight: bold;
            color: red;
        }

        .user-area li.active a {
            color: red;
        }

        .role-area tr td a {
            display: block;
        }

        .role-area tr.active {
            background-color: #f1f7fd;
            border-left: 3px solid #fdc00f;
        }

        .permission-area tr.root {
            background-color: #f1f7fd;
            cursor: pointer;
        }

        .permission-area tr.root td i {
            margin: 3px;
        }

        .permission-area .node {

        }

        .permission-area .node input[type='checkbox'] {
            margin: 0 5px;
        }

        .permission-area .node .parent {
            padding: 5px 0;
        }

        .permission-area .node label {
            font-weight: normal;
            margin-bottom: 0;
            font-size: 12px;
        }

        .permission-area .node .children {
            padding: 0 0 0 20px;
        }

        .permission-area .node .children .child {
            display: inline-block;
            margin: 2px 5px;
        }

        table {
            font-size: 12px;
        }

        .panel-body {
            font-size: 12px;
        }

        .panel-body .form-control {
            font-size: 12px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="luffy-container">
        <div class="col-md-3 user-area">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-address-book-o" aria-hidden="true"></i> 用户信息
                </div>

                <div class="panel-body">
                    <ul>
                        {% for user in user_list %}

                            <li class= {% if user.id|safe == uid %} "active" {% endif %}>
                                <a href="?uid={{ user.id }}">{{ user.name }}</a></li>

                        {% endfor %}
                    </ul>
                </div>

            </div>
        </div>

        <div class="col-md-3 role-area">
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="postType" value="role">
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading">
                        <i class="fa fa-book" aria-hidden="true"></i> 角色
                        {% if uid %}
                            <button type="submit" class="right btn btn-success btn-xs"
                                    style="padding: 2px 8px;margin: -3px;">
                                <i class="fa fa-save" aria-hidden="true"></i>
                                保存
                            </button>
                        {% endif %}
                    </div>
                    <div class="panel-body" style="color: #d4d4d4;padding:10px  5px;">
                        提示：点击用户后才能为其分配角色
                    </div>
                    <table class="table">
                        <thead>
                        <tr>
                            <th>角色</th>
                            <th>选择</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for role in role_list %}
                            <tr {% if role.id|safe == rid %} class="active"  {% endif %}>

                                <td><a href="?{% gen_role_url request role.id %}">{{ role.name }}</a></td>
                                <td>
                                    {% if role.id in user_has_roles_dict %}
                                        <input type="checkbox" name="roles" value="{{ role.id }}" checked/>
                                    {% else %}
                                        <input type="checkbox" name="roles" value="{{ role.id }}"/>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>

                </div>
            </form>
        </div>

        <div class="col-md-6 permission-area">
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="postType" value="permission">
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading">
                        <i class="fa fa-sitemap" aria-hidden="true"></i> 权限分配
                        {% if rid %}
                            <button class="right btn btn-success btn-xs" style="padding: 2px 8px;margin: -3px;">
                                <i class="fa fa-save" aria-hidden="true"></i>
                                保存
                            </button>
                        {% endif %}
                    </div>
                    <div class="panel-body" style="color: #d4d4d4;padding: 10px 5px;">
                        提示：点击角色后，才能为其分配权限。
                    </div>
                    <table class="table">
                        <tbody>
                        {% for item in all_menu_list %}
                            <tr class="root">
                                <td><i class="fa fa-caret-down" aria-hidden="true"></i>{{ item.title }}</td>
                            </tr>
                            <tr class="node">
                                <td>
                                    {% for node in item.children %}
                                        <div class="parent">
                                            {% if node.id in role_has_permissions_dict %}
                                                <input id="permission_{{ node.id }}" name="permissions" value="{{ node.id }}" type="checkbox" checked>
                                            {% else %}
                                                <input id="permission_{{ node.id }}" name="permissions" value="{{ node.id }}" type="checkbox">
                                            {% endif %}


                                            <label for="permission_{{ node.id }}">{{ node.title }}</label>

                                        </div>
                                        <div class="children">
                                            {% for child in node.children %}
                                                <div class="child">
                                                    {% if child.id in role_has_permissions_dict %}
                                                        <input id="permission_{{ child.id }}" name="permissions"
                                                               type="checkbox" value="{{ child.id }}" checked>
                                                    {% else %}
                                                        <input id="permission_{{ child.id }}" name="permissions" type="checkbox" value="{{ child.id }}">
                                                    {% endif %}

                                                    <label for="permission_{{ child.id }}">{{ child.title }}</label>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </form>
        </div>

    </div>
{% endblock %}
{% block js %}
    <script>
        $(function () {
            bindRootPermissionClick();
        });

        function bindRootPermissionClick() {
            $('.permission-area').on('click', '.root', function () {
                var caret = $(this).find('i');
                if (caret.hasClass('fa-caret-right')) {
                    caret.removeClass('fa-caret-right').addClass('fa-caret-down');
                    $(this).next().removeClass('hide');
                } else {
                    caret.removeClass('fa-caret-down').addClass('fa-caret-right');
                    $(this).next().addClass('hide');

                }
            })
        }
    </script>
{% endblock %}

day79 课上笔记以及代码/代码/luffy_permission01/rbac/templates/rbac/menu.html
    <div class="multi-menu">

      {% for menu_k,menu_v in order_dict.items %}
{#        <a href="{{ menu.permissions__url }}" class="{{ menu.class }}">#}
{#            <span class="icon-wrap"><i class="fa {{ menu.permissions__icon }}"></i></span> {{ menu.permissions__title }}</a>#}
        <div class="item">
          <div class="title">{{ menu_v.title }}</div>
          <div class="body {{ menu_v.class }}">
            {% for ermenu in menu_v.children %}
              <a href="{{ ermenu.url }}" class="{{ ermenu.class }}">{{ ermenu.title }}</a>
            {% endfor %}

          </div>

        </div>


      {% endfor %}

    </div>

day79 课上笔记以及代码/代码/luffy_permission01/rbac/templates/rbac/menu_list.html
{% extends 'layout.html' %}

{% block css %}
  <style>

        .permission-area tr.parent {
            background-color: #cae7fd;;
        }

        .menu-body tr.active {
            background-color: #f1f7fd;
            border-left: 3px solid #fdc00f;
        }





  </style>
{% endblock %}
{% block content %}

  <div style="margin-top: 20px;">
    <div class="col-sm-3">
      <div class="panel panel-default">
        <div class="panel-heading">

            <i class="fa fa-book"></i> 菜单管理
          <a href="{% url 'rbac:menu_add' %}" class="btn btn-success btn-sm pull-right" style="padding: 0 4px;"><i class="fa fa-plus"></i>新建</a>

        </div>
        <div class="panel-body">
          <table class="table table-hover" style="margin-top: 5px">
            <thead>
            <tr>
                <th>名称</th>
                <th>图标</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody class="menu-body">
            {% for menu in all_menus %}
                <tr class="{% if mid == menu.pk|safe %}active{% endif %}">

                    <td><a href="{% url 'rbac:menu_list' %}?mid={{ menu.pk }}">{{ menu.title }}</a></td>
                    <td><i class="fa {{ menu.icon }}"></i></td>
                    <td>
                        <a href="{% url 'rbac:menu_edit' menu.pk %}"> <i class="fa fa-edit"></i> </a>
                        <a href="{% url 'rbac:menu_del' menu.pk %}"> <i class="fa fa-trash-o"></i> </a>
                    </td>
                </tr>

            {% endfor %}

            </tbody>
        </table>



        </div>
      </div>

    </div>

    <div class="col-sm-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          <i class="fa fa-cubes"></i> 权限管理
                    <a href="" class="btn btn-primary btn-sm pull-right "
                       style="padding: 2px 8px;margin: -3px;"> <i class="fa fa-scissors"></i> 批量操作</a>
                    <a href="" class="btn btn-success btn-sm pull-right "
                       style="padding: 2px 8px;margin: -3px;"> <i class="fa fa-plus"></i> 新建</a>
        </div>
        <div class="panel-body">
          <table class="table table-hover" style="margin-top: 5px">
            <thead>
            <tr>
                <th>名称</th>
                <th>ULR</th>
                <th>URL别名</th>
                <th>菜单</th>
                <th>所属菜单</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody class="permission-area">
            {% for parent_permission in permission_dict %}
                <tr class="parent">
                    <td><i class="fa fa-caret-down icon"></i> {{ parent_permission.title }}</td>
                    <td>{{ parent_permission.url }}</td>
                    <td>{{ parent_permission.url_name }}</td>
                    <td>{{ parent_permission.menus__title }}</td>
                    <td></td>
                    <td>
                        <a href=""> <i class="fa fa-edit"></i> </a>
                        <a href=""> <i class="fa fa-trash-o"></i> </a>
                    </td>
                </tr>
                {% for child_permission in parent_permission.children %}
                  <tr>
                    <td>{{ child_permission.title }}</td>
                    <td>{{ child_permission.url }}</td>
                    <td>{{ child_permission.url_name }}</td>
                    <td></td>
                    <td>{{ child_permission.parent__title }}</td>
                    <td>
                        <a href=""> <i class="fa fa-edit"></i> </a>
                        <a href=""> <i class="fa fa-trash-o"></i> </a>
                    </td>
                </tr>

                {% endfor %}


            {% endfor %}

            </tbody>
        </table>
        </div>
      </div>

    </div>


  </div>

{% endblock %}



{% block js %}
  <script>
    $('.parent').click(function () {

        // fa-caret-right"
        $(this).find('.icon').toggleClass('fa-caret-right');
        $(this).nextUntil('.parent').toggleClass('hidden');

    })


  </script>


{% endblock %}